mysql:
  image: sameersbn/mysql:latest
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/mysql:/var/lib/mysql

redmine:
  image: sameersbn/redmine:2.6.9
  links:
    - mysql:mysql
  environment:
    - TZ=Asia/Tokyo

    - REDMINE_PORT=80
    - REDMINE_RELATIVE_URL_ROOT=

  ports:
    - "80:80"
  volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
